### ISSUE TITLE
Will there be any detailed info of commands

### ISSUE THREAD

**Issue by loveyanbei** [trentech/ProjectWorlds#58] opened 2017-04-16 11:03 UTC
I cannot do anything according to the instruction
I HAVE TO READ THE SOURCE TO KNOW HOW TO USE.
Will there be any fix?

**Comment by loveyanbei** [comment] 2017-04-16 11:13
To be honest 
The instruction is A PIECE OF SHIT!
No syntax instruction to follow.

**Comment by loveyanbei** [comment] 2017-04-16 11:35
![default](https://cloud.githubusercontent.com/assets/7147471/25070862/c29bcfea-22db-11e7-90b2-f5dbdf96f7b1.png)
Trying to execute 
/world create 
and got only error messages but not help message.

**Comment by trentech** [comment] 2017-04-16 16:00
Yeah it's an issue with Sponge I've been fighting with for over a year now. For some reason if something is incorrect in a subcommand, Sponge outputs the parent Output usage, which is completely useless in most cases. I've complained about it and put in multiple tickets to Sponge but they seem to not care. So I've been attempting to work around this in my dev builds, which are a little better about catching the errors and outputting custom usage output but I've not been able to catch everything so it's pretty inconsistent at the moment. I can do my best but it's likely to continue to be a problem until this is truly fixed in Sponge.

**Comment by loveyanbei** [comment] 2017-04-16 16:08
@trentech 
feeling frustrated
but after reading the source code I successfully created a new world using Mod generator aside overworld

**Comment by macks2008** [comment] 2017-05-03 22:48
@trentech try looking at how other plug-ins handle it. IIRC, Nucleus manages to provide the right help message. For now and until it's fixed, you really ought to have syntax information on the wiki

**Comment by macks2008** [comment] 2017-05-03 22:54
confirmed. Take /nucleus item for instance
i[nucleus has no trouble](http://i.imgur.com/4MX7WRq.png)
just like when people tell me "other users/devs/ops have no trouble, so what are you doing wrong?", well, the same applies here.

**Comment by trentech** [comment] 2017-05-04 14:05
Nucleus provides it's own command usage, working around the same issue. This is already been handled in API 6 builds.

**Comment by macks2008** [comment] 2017-05-04 17:50
so... does that mean I should be able to update and be able to get usage info on your commands now? Or did I misunderstand. Because one way or another, I really need to know how to use these commands if this plugin is going to be any use  to me, and the same goes for anyone else, so this is rather important.

**Comment by macks2008** [comment] 2017-05-06 02:29
@trentech hello? You still haven't given any information on where we can find documentation for when the command help fails as it currently is. Neither /help world import nor /world import nor /world help import actually provide useful information, and there's nothing on the repository's wiki. There is a tiny bit of guidance on the plug-in's thread on spongepower to forums, but nothing helpful in the way of syntax. What are we supposed to do? take our best educated guess (and educated is barely a relevant word here since there's not much information to go on) at the correct syntax for the command?

**Comment by trentech** [comment] 2017-05-06 14:57
OK OK I get it. If you look through the thread, you would find numerous posts of me explaining that in game help is provided by [HelpMe](https://github.com/trentech/HelpMe/releases), which is also linked in the OP. use /hm to list all commands and click around for information and usage. Also enables same features when executing /world. List of commands are clickable.

Also just threw this up, pulled directly from src in the 6.x branch https://github.com/trentech/ProjectWorlds/blob/6.x/commands.txt

Now HelpMe isn't in the 6.x builds anymore as it's built into [ProjectCore](https://github.com/trentech/ProjectCore) which is a library I setup that all my projects now depend on post 6.x. This enables relatively proper usage when running commands, with hints when hovering over arguments and clickable text for more details. Some play around with it, start by clicking on the commands when running /world,

Development builds of all my projects are now available here http://trentech.org/jenkins/ My Jenkins server is still a work in progress so don't expect 24/7 uptime, but should be available most of the time. 

I know everyone is getting real impatient but it's hard for me to find time to work on my projects, so when I do, documentation is the last thing I'm thinking about. It's a grind I keep putting off, which is why I designed the detailed in game help to begin with. I've been spending time lately trying to streamline the process, allow for faster updates without too much manual intervention, hens the Jenkins server. I still have a long list of stuff to do and not a lot of time to do it. Was hoping by now I would have some contributors helping out.

**Comment by macks2008** [comment] 2017-05-06 21:23
maybe you could at least copy paste one of your explanations or perhaps a link to this thread into this repository's wiki so people know to look there. Despite the name HelpMe, it's not particularly obvious that command help is given by a separate plugin. I understand being tired of explaining it, but if the explanation was somewhere more central as I'm suggesting, you hopefully won't have to explain as much. if the wiki had said something as simple as "command syntax documentation is provided by  HelpMe." with perhaps an in-line link as you provided above, I wouldn't be here.

**Comment by macks2008** [comment] 2017-05-08 14:20
@trentech uhhh... I have helpme in the mods folder on both my client and the server skill… And I'm still lost as fuck. Is there a command to run or a GUI to open that I'm missing?

**Comment by macks2008** [comment] 2017-05-11 02:36
@trentech

**Comment by macks2008** [comment] 2017-05-11 17:02
the issue with not documenting stuff is that while it may make perfect sense to you, someone that's not familiar with Java or even if they are but just not your code, well, we have absolutely no bloody clue where to start. Helpme is about as documented and intuitive as PW... which is to say it's confusing AF
@trentech I know it must be daunting, but documentation is a must if you expect people to actually be able to use  the software, at least without asking 2000 questions (something else you've expressed frustration about). If you think you have no idea where to start documenting the mod, imagine how we feel trying to work with neither experience nor effective documentation? The fact I even managed to figure out how to use /world gamerule on the nether is a miracle...
@loveyanbei perhaps you can enlighten me, seeing as the developer is apparently in over his head?

**Comment by trentech** [comment] 2017-05-11 19:15
Seriously? I gave you everything you need to figure it out on your own. Ask someone on the forum like everyone else. I'm not holding your hand.

**Closed by trentech** 2017-05-11 19:15 UTC

**Comment by macks2008** [comment] 2017-05-12 17:18
I could be really sarcastic here and point out a bunch of problems with the "help" you gave me, but I don't think it's worth my effort.

**Comment by trentech** [comment] 2017-05-13 12:28
Next time, work on your approach, and you might get better results. For starters, don't be an ass. And be precise. What are you doing, how are you doing it, what specifically doesn't work, paste-bin your server log, list the commands you tried, every detail makes all the difference. Give me something to work with so I can help.

Sorry, you caught me on a bad couple of weeks. All I've wanted to do is go home and pass out for 12 hours, but I have to pay the bills so I'm a bit burnt out. Once I get my barrings back, I'm going to start working on some documentation.

**Comment by macks2008** [comment] 2017-05-13 13:20
No worries, and looking back I was being a bit of an arse about it (even if you weren't much better... but I have less of an excuse since I can sleep sufficiently). Anyway, I've managed to at least try importing and loading the world. The issue I'm facing now is no longer a matter of "I don't have command syntax", and I'm discussing it at the bottom of the forum thread (I've made 2 posts on it so far) if you feel like helping.
